import json
import os

MAX_RUNTIME_IN_SECONDS_ENVVAR = 'TRAINING_MAX_RUNTIME_IN_SECONDS'
INSTANCE_COUNT_ENVVAR = 'TRAINING_INSTANCE_COUNT'
INSTANCE_TYPE_ENVVAR = 'TRAINING_INSTANCE_TYPE'
IMAGE_URI_ENVVAR = 'TRAINING_IMAGE'
IAM_ROLE_EVVAR = 'TRAINING_ROLE_ARN'
SUBNET_ENVVAR = 'TRAINING_SUBNET'
SECURITY_GROUP_BATCH_ENVVAR = 'TRAINING_SECURITY_GROUP'
TRAINING_INPUT_BUCKET_ENVVAR = 'TRAIN_BUCKET'

MODELS_BUCKET_ENVVAR = 'MODELS_BUCKET'
TRAINED_MODELS_ENVVAR = 'TRAINED_MODELS'
MODEL_NAME_ENVVAR = 'MODEL_NAME'

MODELS_BUCKET_SUBDIR = 'models'
TRAINING_INPUT_BUCKET_SUBDIR = 'rewarded_decisions'

VOLUME_SIZE_IN_GB = 3  # ?

JOB_NAME_PREFIX = 'improve-train-job'
MODEL_NAME_REGEXP = "^[\w\- .]+$"
AWS_BUCKET_PREFIX = 's3://'
AWS_S3_PATH_SEP = '/'

IMPROVE_CONFIG = json.loads(os.getenv('IMPROVE_CONFIG'))

EXPECTED_TRAINER_OUTPUT_FILENAME = 'model.tar.gz'
EXPECTED_MODELS_COUNT = 2