IAM_ROLE_EVVAR = 'TRAINING_ROLE_ARN'
SUBNET_ENVVAR = 'TRAINING_SUBNET'
SECURITY_GROUP_BATCH_ENVVAR = 'TRAINING_SECURITY_GROUP'
TRAIN_BUCKET_ENVVAR = 'TRAIN_BUCKET'

MODELS_BUCKET_ENVVAR = 'MODELS_BUCKET'
MODEL_NAME_HYPERPARAMS_KEY = 'model_name'
HYPERPARAMETERS_KEY = 'hyperparameters'

SERVICE_NAME_ENVVAR = 'SERVICE_NAME'
STAGE_ENVVAR = 'STAGE'

JOB_NAME_PREFIX = 'improve-train-job'


SAGEMAKER_TRAIN_JOB_NAME_SEPARATOR = '-'
SPECIAL_CHARACTERS_REGEXP = "[^A-Za-z0-9-]"
DIGITS_DT_REGEXP = '\.|\-|:| '
SAGEMAKER_MAX_TRAIN_JOB_NAME_LENGTH = 63
# min 4 chars for stage
MIN_STAGE_LENGTH = 4
# min 8 chars for model name
MIN_MODEL_NAME_LENGTH = 8

EXPECTED_TRAINER_OUTPUT_FILENAME = 'model.tar.gz'

EVENT_MODEL_NAME_KEY = 'model_name'
EVENT_WORKER_INSTANCE_TYPE_KEY = 'instance_type'
EVENT_WORKER_COUNT_KEY = 'instance_count'
EVENT_MAX_RUNTIME_KEY = 'max_runtime'
EVENT_VOLUME_SIZE_KEY = 'volume_size'
EVENT_IMAGE_KEY = 'image'

EXPECTED_EVENT_ENTRIES = [EVENT_MODEL_NAME_KEY, EVENT_WORKER_INSTANCE_TYPE_KEY, EVENT_WORKER_COUNT_KEY, EVENT_MAX_RUNTIME_KEY]
